//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservaDeVuelos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AEROLINEAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AEROLINEAS()
        {
            this.RESERVAS_ASIENTOS = new HashSet<RESERVAS_ASIENTOS>();
            this.PRECIOS_VUELOS = new HashSet<PRECIOS_VUELOS>();
            this.ASIGNA_AP_AL = new HashSet<ASIGNA_AP_AL>();
            this.AVIONES = new HashSet<AVIONES>();
        }
    
        public int COD_AEROLINEA { get; set; }
        public string NOM_AEROLINEA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESERVAS_ASIENTOS> RESERVAS_ASIENTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRECIOS_VUELOS> PRECIOS_VUELOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASIGNA_AP_AL> ASIGNA_AP_AL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVIONES> AVIONES { get; set; }
    }
}
