//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservaDeVuelos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASIGNA_AP_AL
    {
        public int COD_AP_AL { get; set; }
        public int COD_PAIS_REGION { get; set; }
        public int COD_AERO { get; set; }
        public int COD_AEROLINEA { get; set; }
    
        public virtual AEROLINEAS AEROLINEAS { get; set; }
        public virtual AEROPUERTOS AEROPUERTOS { get; set; }
        public virtual PAISES_REGIONES PAISES_REGIONES { get; set; }
    }
}
