//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservaDeVuelos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAISES_REGIONES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PAISES_REGIONES()
        {
            this.ASIGNA_AP_AL = new HashSet<ASIGNA_AP_AL>();
            this.RESERVAS_DESTINOS = new HashSet<RESERVAS_DESTINOS>();
            this.PRECIOS_VUELOS = new HashSet<PRECIOS_VUELOS>();
            this.RESERVAS_DESTINOS1 = new HashSet<RESERVAS_DESTINOS>();
            this.PRECIOS_VUELOS1 = new HashSet<PRECIOS_VUELOS>();
        }
    
        public int COD_PAIS_REGION { get; set; }
        public string COD_PAIS { get; set; }
        public string COD_REGION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASIGNA_AP_AL> ASIGNA_AP_AL { get; set; }
        public virtual PAISES PAISES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESERVAS_DESTINOS> RESERVAS_DESTINOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRECIOS_VUELOS> PRECIOS_VUELOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESERVAS_DESTINOS> RESERVAS_DESTINOS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRECIOS_VUELOS> PRECIOS_VUELOS1 { get; set; }
        public virtual REGIONES REGIONES { get; set; }
    }
}
