//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservaDeVuelos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROC_PAGOS_VUELOS
    {
        public int COD_PROC_PAGO_VUELO { get; set; }
        public int COD_RESERVA { get; set; }
        public int COD_TIPO_PAGO { get; set; }
        public int COD_PRECIO_VUELO { get; set; }
        public decimal TOTAL_MONTO { get; set; }
    
        public virtual PRECIOS_VUELOS PRECIOS_VUELOS { get; set; }
        public virtual RESERVAS_VUELOS RESERVAS_VUELOS { get; set; }
        public virtual TIPOS_PAGOS TIPOS_PAGOS { get; set; }
    }
}
