//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservaDeVuelos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVAS_DESTINOS
    {
        public int COD_RESERVA_DESTINO { get; set; }
        public int COD_OPC_VUELO { get; set; }
        public System.DateTime SALIDA { get; set; }
        public Nullable<System.DateTime> RETORNO { get; set; }
        public int ORIGEN { get; set; }
        public int DESTINO { get; set; }
        public int USUARIO { get; set; }
    
        public virtual OPC_VUELOS OPC_VUELOS { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
