//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservaDeVuelos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVAS_VUELOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RESERVAS_VUELOS()
        {
            this.PROC_PAGOS_VUELOS = new HashSet<PROC_PAGOS_VUELOS>();
        }
    
        public int COD_RESERVA { get; set; }
        public int COD_USUARIO { get; set; }
        public int COD_RESERVA_DESTINO { get; set; }
        public int COD_RESERVA_ASIENTO { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROC_PAGOS_VUELOS> PROC_PAGOS_VUELOS { get; set; }
        public virtual RESERVAS_ASIENTOS RESERVAS_ASIENTOS { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
