//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservaDeVuelos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVAS_ASIENTOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RESERVAS_ASIENTOS()
        {
            this.RESERVAS_VUELOS = new HashSet<RESERVAS_VUELOS>();
        }
    
        public int COD_RESERVA_ASIENTO { get; set; }
        public int COD_TIP_VUELO { get; set; }
        public int ASIENTO { get; set; }
        public int AEROLINEA_AEROPUERTO { get; set; }
        public int COD_AVION { get; set; }
        public int COD_USUARIO { get; set; }
    
        public virtual AEROLINEA_AEROPUERTO AEROLINEA_AEROPUERTO1 { get; set; }
        public virtual AVIONES AVIONES { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESERVAS_VUELOS> RESERVAS_VUELOS { get; set; }
        public virtual TIPO_VUELOS TIPO_VUELOS { get; set; }
    }
}
